alert("Who are you?")
alert("And where are you from?")
alert("Where do you live?")
document. write ("Who are you?")
document. write ("<div>And where are you from?</div>")
document. write ("<div>Where do you live?</div>")
